export const availableGenres = [
  { name: 'Action', slug: 'action' },
  { name: 'Adventure', slug: 'adventure' },
  { name: 'Comedy', slug: 'comedy' },
  { name: 'Drama', slug: 'drama' },
  { name: 'Sci-Fi', slug: 'sci-fi' },
  { name: 'Space', slug: 'space' },
  { name: 'Mystery', slug: 'mystery' },
  { name: 'Magic', slug: 'magic' },
  { name: 'Supernatural', slug: 'supernatural' },
  { name: 'Police', slug: 'police' },
  { name: 'Fantasy', slug: 'fantasy' },
  { name: 'Sports', slug: 'sports' },
  { name: 'Romance', slug: 'romance' },
  { name: 'Cars', slug: 'cars' },
  { name: 'Slice of Life', slug: 'slice-of-life' },
  { name: 'Racing', slug: 'racing' },
  { name: 'Horror', slug: 'horror' },
  { name: 'Psychological', slug: 'psychological' },
  { name: 'Thriller', slug: 'thriller' },
  { name: 'Martial Arts', slug: 'martial-arts' },
  { name: 'Super Power', slug: 'super-power' },
  { name: 'School', slug: 'school' },
  { name: 'Ecchi', slug: 'ecchi' },
  { name: 'Vampire', slug: 'vampire' },
  { name: 'Historical', slug: 'historical' },
  { name: 'Military', slug: 'military' },
  { name: 'Dementia', slug: 'dementia' },
  { name: 'Mecha', slug: 'mecha' },
  { name: 'Demons', slug: 'demons' },
  { name: 'Doujinshi', slug: 'doujinshi' },
  { name: 'Mahou Shoujo', slug: 'mahou-shoujo' },
  { name: 'Mahou Shounen', slug: 'mahou-shounen' },
  { name: 'Gore', slug: 'gore' },
  { name: 'Law', slug: 'law' },
  { name: 'Cooking', slug: 'cooking' },
  { name: 'Mature', slug: 'mature' },
  { name: 'Medical', slug: 'medical' },
  { name: 'Political', slug: 'political' },
  { name: 'Tokusatsu', slug: 'tokusatsu' },
  { name: 'Youth', slug: 'youth' },
  { name: 'Workplace', slug: 'workplace' },
  { name: 'Crime', slug: 'crime' },
  { name: 'Zombies', slug: 'zombies' },
  { name: 'Documentary', slug: 'documentary' },
  { name: 'Family', slug: 'family' },
  { name: 'Food', slug: 'food' },
  { name: 'Friendship', slug: 'friendship' },
  { name: 'Tragedy', slug: 'tragedy' },
  { name: 'Isekai', slug: 'isekai' },
];
